Found the cause for issue 121: uploading an iCalendar file with all-day events produces "AttributeError: 'datetime.date' object has no attribute 'date'" when you try to subsequently view the calendar.